spring.application.name=backend

server.port=8080

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# JWT
jwt.expiration-ms=86400000
