name: Deploy to Lightsail

on:
  workflow_dispatch:  # 수동 실행만 허용

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH 접속 후 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 30m
          script: |
            cd ~/headongmono
            git pull origin main
            echo "DB_URL=${{ secrets.DB_URL }}" > .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            sudo docker-compose up --build -d
